### ISSUE TITLE
Npm conflict with project name

### ISSUE THREAD

**Issue by Flignats** [GildedFinance/angular-request-network#6]
Npm complains that the npm package is the same as the project name and then errors and does not install.

Changing the project name in the package.json fixes the issue, however, this may be a good reason to adopt the 'ngx' naming convention while an 'ngx-request-network' does not yet exist.

**Comment by edyrkaj** [comment]
hi @Flignats, thank you for your suggestion. 
Please can you provide more information about your try and angular version that you are using or other feedbacks if you was able to use this package.

**Comment by edyrkaj** [comment]
@Flignats please you can try with last updated version: 1.1.5 which I have published today.
Thank you.

**Comment by Flignats** [comment]
Cloned the repo  => Success
npm install  => Success
npm install angular-request-network --save  => Failed

```
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "angular-request-network" under a package
npm ERR! also called "angular-request-network". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
```

angular-request-network will install if the project name is changed in package.json. However,  Ialso needed to add the ```HttpClientModule``` to the ```app.module``` in order for the project to compile successfully. 

```"@angular/core": "6.0.5",```

**Comment by edyrkaj** [comment]
@Flignats thanks for sharing details. I will came back to you after some debugging process.

**Comment by edyrkaj** [comment]
This has been updated since this reported error is fixed in master branch.
